# Generated by Django 2.0.13 on 2019-06-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='task',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
    ]
