# Generated by Django 2.0.13 on 2019-06-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0002_auto_20190627_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
