# Generated by Django 2.0.13 on 2019-06-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0003_todo_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(blank=True, choices=[('Highest', 'Highest'), ('Average', 'Average'), ('Low', 'Low'), ('None', 'None')], default='None', max_length=25, null=True),
        ),
    ]
