# Generated by Django 2.0.13 on 2019-06-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0004_auto_20190628_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.CharField(blank=True, choices=[('Highest', 'Highest'), ('Average', 'Average'), ('None', 'None')], default='None', max_length=25, null=True),
        ),
    ]
